// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clatvqonvzdkdfusufxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsYXR2cW9udnpka2RmdXN1Znh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NTUzOTcsImV4cCI6MjA1MjAzMTM5N30.FfyB268VUU2JJdmsyOpAZHVJCUMV1ppMDYlCiGt4ye0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);